name: smart_hospital
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  # تم إضافة المكتبة هنا مع ضبط المسافات لتقرأها الفلاتر صح
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  supabase_flutter: ^2.14.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#1B3A4B"
  adaptive_icon_foreground: "assets/images/shh_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/hospital_bg.png
    - assets/images/doctor_onboarding.png
    - assets/images/care_onboarding.png
    - assets/images/connect_onboarding.png
    # تم تصحيح السطر ده عشان يقرأ كل الصور اللي في الفولدر من غير أخطاء
    - assets/images/

  # إذا كان عندك خطوط مخصصة مستقبلاً ضيفها هنا تحت الـ fonts